### ISSUE TITLE
Website no longer working due to "bad credentials"

### ISSUE THREAD

**Issue by marcolussetti** [vesoft-inc/github-statistics#70]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

The website is not working at all now. When a project is being typed in, nothing happens.
When you check the browser console, it gets filled with 401 errors from the GitHub GraphQL API with the response of "Bad credentials"

**Your Environments (__required__)**

* OS: Tested on Firefox and Chromium (Linux)
* Commit id: N/A (current live version

**How To Reproduce(__required__)**

1. Got to https://vesoft-inc.github.io/github-statistics/
2. Type in any repository
3. The button never becomes enabled and no data is ever loaded

**Expected behavior**

Data is loaded, graphs are shown

**Additional context**

**Comment by marcolussetti** [comment]
Thank you so much @wey-gu & @nianiaJR !

**Comment by Relequestual** [comment]
Looks like the issue has come back.

**Comment by nianiaJR** [comment]
> Looks like the issue has come back.

what's the problem? I've tested it in my local env, it looks ok.

**Comment by nielifeng** [comment]
index.js:286 Uncaught (in promise) Error: GraphQL Error (Code: 401): {"response":{"message":"Bad credentials","documentation_url":"https://docs.github.com/graphql","status":401},"request":{"query":"\n      query searchRepository($query: String!){\n        search(query: $query, first: 5, type: REPOSITORY) {\n          codeCount\n          nodes {\n            ...on Repository {\n              nameWithOwner\n            }\n          }\n        }\n      }\n    ","variables":{"query":"Ap"}}}
    at e.<anonymous> (index.js:286:21)
    at index.js:137:19
    at Object.next (index.js:67:14)
    at a (index.js:19:24)

**Comment by nielifeng** [comment]
POST https://api.github.com/graphql 401 (Unauthorized)

**Comment by wey-gu** [comment]
I think @nielifeng meant the serving version on github pages, that won't work now with the change removing hardcoded credentials.

To enable that, we could further:

- provide a configuration interface to enable a user to fill in their own API token
- or, register it as a github application, and implement oauth2 flow to get github user's token as they need

**Comment by jerviscui** [comment]
> POST [api.github.com/graphql](https://api.github.com/graphql) 401 (Unauthorized)

Same with me.

**Comment by nianiaJR** [comment]
It's like that you don't have the access to the Github API, have you config your own token here https://github.com/vesoft-inc/github-statistics/blob/master/.env ?

It has been described in the README

**Comment by alwqx** [comment]
Hi all, I fix this problem in pr https://github.com/vesoft-inc/github-statistics/pull/74 .

please check and review my work.

**Comment by MrSharpp** [comment]
same problem

**Comment by simonmichael** [comment]
This looks like a cool project! Comparable to the great https://star-history.com .

It's a pity the public demo doesn't work. Could it be fixed again ?

**Comment by mig82** [comment]
The public demo isn't working anymore.

**Comment by mig82** [comment]
Still not working
